language: go
# command to install dependencies
install:
  - sudo pip install -r requirements.txt
  - python helpers/pair_steps.py

before_script:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/btcsuite/btcd/btcec
  - go get github.com/btcsuite/btcutil/base58
  - go get golang.org/x/crypto/ripemd160
  - go get github.com/gorilla/mux
   
# command to run tests
script: 
  - ginkgo -r --keepGoing 
